# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Ron Ferens
name: Ron Ferens
position: Director of Architecture and AI at Blink Technologies, Inc. | PhD Candidate 
email: ronferens@gmail.com
description: >-
  "I'm an algorithm engineer specializing in machine-learning and deep-learning applications for computer vision and image processing. My work spans 2D and 3D domains, addressing various needs like hand and body tracking, expression recognition, large-scale visual localization, and eyes and gaze tracking.
My academic focus revolves around absolute camera pose estimation, where I explore end-to-end learning methods. I'm passionate about leveraging algorithms to solve real-world problems and contribute to the evolving landscape of computer vision."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ronferens.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ronferens
github_username: ronferens
google_scholar: LsWZsgIAAAAJ

# Build settings
theme: minima
plugins:
  - jekyll-feed

sass:
  style: compact

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
